[build]
builder = "nixpacks"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
healthcheckPath = "/auth/login"
healthcheckTimeout = 300

[env]
JAVA_OPTS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
ALLOWED_ORIGINS = "*"
JAVA_TOOL_OPTIONS = "-Xmx512m"

