[build]
builder = "nixpacks"
buildCommand = "chmod +x mvnw && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT $JAVA_OPTS -jar target/taller1-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/auth/login"
healthcheckTimeout = 300

[nixpacks]
javaVersion = "17"

[env]
JAVA_OPTS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
ALLOWED_ORIGINS = "*"

# Railway configures these variables automatically
# PORT, DATABASE_URL, etc.

